---

- name: Include Vault secrets vars
  include_vars:
    file: "vault-secrets.yml"
    name: secrets

- name: Add credentials to Vault Master key-value store
  uri:
    url: "http://{{ vault.host.ip }}:8200/v1/secret/data/user/{{ item.name }}"
    method: POST
    body: "{{ item.value }}"
    body_format: json
    headers:
      Content-Type: "application/json"
      X-Vault-Token: "{{ vault_root_token }}"
    status_code: 200, 204
    environment:
      VAULT_TOKEN: "{{ vault_root_token }}"
  with_items: "{{ secrets.credentials }}"